### ISSUE TITLE
EmoteCraft incompatibility

### ISSUE THREAD

**Issue by BakinDP** [McVader34/Serious-Player-Animations#1]
Animations do not play if EmoteCraft (2.2.7-b build 50 for 1.20.1) is installed.

Steps to reproduce:
1. Install Serious Player Animations and EmoteCraft at the same time
2. Launch the game
3. Serious Player Animations doesn't work, EmoteCraft works

Small note: if NotEnoughAnimations is present, its animations are still played.

**Comment by McVader34** [comment]
Fixed in v1.0.1
