### ISSUE TITLE
Add Compatibility with First Person View

### ISSUE THREAD

**Issue by Sarund9** [McVader34/Serious-Player-Animations#13]
Currently using alongside [First Person View](https://modrinth.com/mod/first-person-model) looks like this:
![image](https://github.com/McVader34/Serious-Player-Animations/assets/53350334/555caa15-3ca1-424f-9ac4-f1052a95c06e)

The player's head is being rendered, which blocks the view.
Other than this the mods work out of the box.

**Comment by McVader34** [comment]
I can't seem to recreate this bug. I'm on 1.20.1 and the mods are working fine together (head is invisible). Can you provide what version you are on and a list of mods to help narrow down the issue.

**Comment by Sarund9** [comment]
I did some testing and this isn't related to this mod. It is related to FastAnim and First Person View
