### ISSUE TITLE
A mod thief.

### ISSUE THREAD

**Issue by Mozork01** [McVader34/Serious-Player-Animations#19]
I believe someone has stolen your work. The animations are identical to yours. When you open the file of their mod, everything is identical to yours.

https://www.curseforge.com/minecraft/mc-mods/pandas-animations

**Comment by Mozork01** [comment]
I also left a comment on his mod saying that it looked remarkably similar to yours. However, the comment section no longer exists.

**Comment by McVader34** [comment]
Thanks for letting me know
