### ISSUE TITLE
Cape Posing While running

### ISSUE THREAD

**Issue by necromancertype** [McVader34/Serious-Player-Animations#27]
When the player starts running, the cape stays in the same place(flies separately from the player's body).
I'd really appreciate it if you could fix it. Your mod is gorgeous!
![cape pose bug](https://github.com/McVader34/Serious-Player-Animations/assets/141460733/55f94388-6b4c-4f87-b47c-1bdfb32c2b4c)

**Comment by McVader34** [comment]
Duplicate
