### ISSUE TITLE
Priority Problems

### ISSUE THREAD

**Issue by DogeKingChris** [McVader34/Serious-Player-Animations#36]
All the animations have too high priorities compared to all other animations in game. Basically what I mean is that the idle animation plays over animations from other mods. You could fix a LOOOOOOOOT of compatibility issues with mods by simply having a system which puts this mod's animations under others in priority. Or replace the vanilla animations with these (i have a feeling youve done something else to have these animations in place rather than just simply replacing the animations). Considering the config files dont make the vanilla animations come back when turning the mod's animations off, im assuming you removed them then added the custom animations over them? Idk how modding works but that's what I assume. Either way, make it so other mod's animations can player over yours.

**Comment by McVader34** [comment]
This mod uses player animator for animations. If every mod used player animator there wouldn't be any problem with priority. However, a lot of mods have their own custom animation systems and it's not that simple to add compatibility. Most of the time I have to check the mods events to disable SPAs animations at the correct moments and to know which body parts to disable. Also I have not removed the vanilla animations. There's just a bug with the config at the moment. I am looking for ways to add compatibility for some mods that use similar or the same animation systems. But for now I mostly just have to add compatibility one mod at a time.

**Comment by DogeKingChris** [comment]
Ah well that's my bad, sorry

**Comment by DogeKingChris** [comment]
Misconception
