### ISSUE TITLE
Sitting doesn't work properly with some mods

### ISSUE THREAD

**Issue by ghost** [McVader34/Serious-Player-Animations#4]
This might be related to known issues but I'll report it so you can keep track of this.
The player model will just stand when you sit using something like a chair or sit command.

Ps. I'm really glad there's another player animation mod that works on 1.20 that is also compatible enough. Looking forward to seeing even more animations and polishing.

https://github.com/McVader34/Serious-Player-Animations/assets/153728464/04cf25b4-d212-4c32-ae29-cca36c74f8e7

**Comment by McVader34** [comment]
Fixed in V1.0.2
