### ISSUE TITLE
Cape appears disconnected. 

### ISSUE THREAD

**Issue by McVader34** [McVader34/Serious-Player-Animations#5]
Cape is detached from player during animations.

**Comment by Riyuukii** [comment]
any update? ^^

**Comment by McVader34** [comment]
I have a fix for the next update so it acts like how the elytra does now. However it still looks weird in some situation like swinging a sword.

**Comment by Riyuukii** [comment]
> I have a fix for the next update so it acts like how the elytra does now. However it still looks weird in some situation like swinging a sword.

that would be great, can't wait for the new update!
